apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: team-frontend-api-dev
  namespace: dev
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:*
spec:
  chartGitPath: api
  releaseName: team-frontend-api-dev
  values:
    image: 
      repository: localhost:5000/api
      tag: 07b585ae22b53ab7e6c5c35aedb85d19a2b649aa
    ingress:
      hostname: api-dev.dev.idiotz.nl
    autoscaler:
      maxReplicas: 3
      targetCPUUtilizationPercentage: 10