---
apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: team-frontend-dev-api
  namespace: dev
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:dev-*
spec:
  namespace: dev
  chartGitPath: api
  releaseName: team-frontend-dev
  values:
    image:
      repository: reg.dev.idiotz.nl/api
      tag: dev-84e78115e22a963f1e02bce948efbd73539188b2
    ingress:
      hostname: api-dev.dev.idiotz.nl
    service:
      annotations:
        getambassador.io/config: |
          apiVersion: ambassador/v0
          kind:  Mapping
          name:  api_mapping_dev
          prefix: "/"
          rewrite: ""
          host: api-dev.dev.idiotz.nl
          service: team-frontend-dev-api.dev
    autoscaler:
      maxReplicas: 3
      targetCPUUtilizationPercentage: 10
