kind: pipeline
name: default

steps:
  - name: build-branch
    image: plugins/docker
    settings:
      repo: reg.dev.idiotz.nl/api
      username: drone
      password: blabla
      tags:
        - ${DRONE_BRANCH}
        - ${DRONE_BRANCH}-${DRONE_COMMIT}

      cache_from:
        - reg.dev.idiotz.nl/api:latest
        - reg.dev.idiotz.nl/api:${DRONE_BRANCH}
    when:
      branch:
        exclude:
          - master

  - name: build-tags
    image: plugins/docker
    settings:
      repo: reg.dev.idiotz.nl/api
      tags:
        - ${DRONE_TAG}

      cache_from:
        - reg.dev.idiotz.nl/api:master
    when:
      event:
        - tag

  - name: slack
    image: plugins/slack
    settings:
      webhook: https://hooks.slack.com/services/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
      channel: drone-build
      username: Drone
    when:
      status:
        - success
        - failure
steps:
  - name: build-branch
    image: plugins/docker
    settings:
      repo: reg.dev.idiotz.nl/api
      tags:
        - ${DRONE_BRANCH}
        - ${DRONE_BRANCH}-${DRONE_COMMIT}

      cache_from:
        - reg.dev.idiotz.nl/api:latest
        - reg.dev.idiotz.nl/api:${DRONE_BRANCH}
    when:
      branch:
        exclude:
          - master

  - name: build-tags
    image: plugins/docker
    settings:
      repo: reg.dev.idiotz.nl/api
      tags:
        - ${DRONE_TAG}

      cache_from:
        - reg.dev.idiotz.nl/api:master
    when:
      event:
        - tag

  - name: slack
    image: plugins/slack
    settings:
      webhook: https://hooks.slack.com/services/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
      channel: drone-build
      username: Drone
    when:
      status:
        - success
        - failure
