# Default values for api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
autoscaler:
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
image:
  repository: reg.dev.idiotz.nl/api
  tag: latest
ingress:
  hostname: api-test.dev.idiotz.nl
resources:
  requests:
    cpu: 100m
  limits:
    memory: 100M
    cpu: 1
