# Default values for api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
autoscaler:
  maxReplicas: 10
  targetCPUUtilizationPercentage: 10
annotations:
  sidecar.istio.io/inject: 'false'
image:
  pullPolicy: Always
ingress:
  enabled: true
  tls: true
  hostname: api.dev.idiotz.nl
resources:
  requests:
    cpu: 100m
  limits:
    memory: 100M
    cpu: 1
