{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ .Chart.Name | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{- if not .Values.ingress.tls }}
    ingress.kubernetes.io/ssl-redirect: 'false'
    {{- end }}
{{ toYaml .Values.ingress.annotations | indent 4 }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    - secretName: {{ template "fullname" . }}-tls
    {{- if .Values.ingress.hostname }}
      hosts:
      - {{ .Values.ingress.hostname }}
    {{- end -}}
  {{- end }}
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "fullname" . }}
          servicePort: {{ .Values.service.http.externalPort }}
  {{- if .Values.ingress.hostname }}
    host: {{ .Values.ingress.hostname }}
  {{- end -}}
{{- end -}}
