apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ .Chart.Name | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.http.externalPort }}
    targetPort: {{ .Values.service.http.internalPort }}
    protocol: TCP
    name: http
  selector:
    app: {{ .Chart.Name | quote }}
    release: {{ .Release.Name }}
