apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: team-frontend-api
  namespace: prod
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~0.1
spec:
  chartGitPath: api
  releaseName: team-frontend-api
  values:
    image: 
      repository: reg.dev.idiotz.nl/api
      tag: latest
    autoscaler:
      maxReplicas: 10
      targetCPUUtilizationPercentage: 50
