apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: team-frontend-prod-api
  namespace: prod
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~0.1
spec:
  namespace: prod
  chartGitPath: api
  releaseName: team-frontend-prod
  values:
    image: 
      repository: reg.dev.idiotz.nl/api
      tag: latest
    ingress:
      hostname: api.dev.idiotz.nl
    service:
      annotations:
        getambassador.io/config: |
          apiVersion: ambassador/v0
          kind:  Mapping
          name:  api_mapping_prod
          # prefix: /
          host: api.dev.idiotz.nl
          service: team-frontend-prod-api.prod
    autoscaler:
      maxReplicas: 10
      targetCPUUtilizationPercentage: 50
