apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: team-frontend-api-rc
  namespace: stg
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:stg-*
spec:
  chartGitPath: api
  releaseName: team-frontend-api-rc
  values:
    ingress:
      hostname: api-stg.dev.idiotz.nl
    autoscaler:
      maxReplicas: 5
      targetCPUUtilizationPercentage: 70